#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Calibration task definition module
Defines types and configurations for all calibration tasks
"""

from enum import Enum
from dataclasses import dataclass
from typing import Optional, List


class CalibrationTaskType(Enum):
    """Calibration task type enumeration"""
    IMU_INTRINSIC = "imu_intrinsic"  # data5: IMU intrinsic calibration (3 IMUs)
    CAM_LR_FRONT_INTRINSIC = "cam_lr_front_intrinsic"  # data1: Left-right front camera intrinsic
    CAM_LR_FRONT_EXTRINSIC = "cam_lr_front_extrinsic"  # data6: Left-right front camera extrinsic
    CAM_LR_EYE_INTRINSIC = "cam_lr_eye_intrinsic"  # data2: Left-right eye camera intrinsic
    CAM_LR_EYE_EXTRINSIC = "cam_lr_eye_extrinsic"  # data7: Left-right eye camera extrinsic
    CAM_L_INTRINSIC = "cam_l_intrinsic"  # data3: Left eye camera intrinsic
    CAM_L_EXTRINSIC = "cam_l_extrinsic"  # data8: Left eye camera extrinsic
    CAM_R_INTRINSIC = "cam_r_intrinsic"  # data4: Right eye camera intrinsic
    CAM_R_EXTRINSIC = "cam_r_extrinsic"  # data9: Right eye camera extrinsic


@dataclass
class CalibrationTask:
    """Calibration task definition"""
    task_type: CalibrationTaskType
    data_dir: str  # Data directory (data1-data9: data1-4 for camera intrinsics, data5 for IMU intrinsic, data6-9 for camera-IMU extrinsics)
    script_name: str  # Script name to execute
    script_args: List[str]  # Script arguments
    expected_output_files: List[str]  # Expected output file list
    s3_upload_path_template: str  # S3 upload path template, uses {device_id} placeholder
    
    def get_s3_path(self, device_id: str, filename: str = "{filename}") -> str:
        """Get S3 upload path"""
        return self.s3_upload_path_template.format(device_id=device_id, filename=filename)


# Define all calibration task configurations
CALIBRATION_TASKS = {
    CalibrationTaskType.IMU_INTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.IMU_INTRINSIC,
        data_dir="data5",
        script_name="calib_imus_intrinsic.py",
        script_args=[],
        expected_output_files=[
            "imu_mid_0.yaml",
            "imu_right_1.yaml",
            "imu_left_2.yaml"
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_intrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_LR_FRONT_INTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_LR_FRONT_INTRINSIC,
        data_dir="data1",
        script_name="calib_cams_intrinsic.py",
        script_args=["front"],
        expected_output_files=[
            "cam_lr_front_intrinsic-camchain.yaml"
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_lr_front_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_LR_FRONT_EXTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_LR_FRONT_EXTRINSIC,
        data_dir="data6",
        script_name="calib_cams_imu_extrinsic.py",
        script_args=["front"],
        expected_output_files=[
            "imus-cam_lr_front_extrinsic-camchain.yaml"  # Camchain file generated by extrinsic calibration
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_lr_front_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_LR_EYE_INTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_LR_EYE_INTRINSIC,
        data_dir="data2",
        script_name="calib_cams_intrinsic.py",
        script_args=["eye"],
        expected_output_files=[
            "cam_lr_eye_intrinsic-camchain.yaml"
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_lr_eye_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_LR_EYE_EXTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_LR_EYE_EXTRINSIC,
        data_dir="data7",
        script_name="calib_cams_imu_extrinsic.py",
        script_args=["eye"],
        expected_output_files=[
            "imus-cam_lr_eye_extrinsic-camchain.yaml"  # Camchain file generated by extrinsic calibration
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_lr_eye_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_L_INTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_L_INTRINSIC,
        data_dir="data3",
        script_name="calib_cams_intrinsic.py",
        script_args=["left"],
        expected_output_files=[
            "cam_l_intrinsic-camchain.yaml"
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_l_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_L_EXTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_L_EXTRINSIC,
        data_dir="data8",
        script_name="calib_cams_imu_extrinsic.py",
        script_args=["left"],
        expected_output_files=[
            "imus-cam_l_extrinsic-camchain.yaml"  # Camchain file generated by extrinsic calibration
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_l_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_R_INTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_R_INTRINSIC,
        data_dir="data4",
        script_name="calib_cams_intrinsic.py",
        script_args=["right"],
        expected_output_files=[
            "cam_r_intrinsic-camchain.yaml"
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_r_extrinsic/{filename}"
    ),
    CalibrationTaskType.CAM_R_EXTRINSIC: CalibrationTask(
        task_type=CalibrationTaskType.CAM_R_EXTRINSIC,
        data_dir="data9",
        script_name="calib_cams_imu_extrinsic.py",
        script_args=["right"],
        expected_output_files=[
            "imus-cam_r_extrinsic-camchain.yaml"  # Camchain file generated by extrinsic calibration
        ],
        s3_upload_path_template="{device_id}/v1/results/imus_cam_r_extrinsic/{filename}"
    ),
}


def get_task_by_type(task_type: CalibrationTaskType) -> CalibrationTask:
    """Get task configuration by task type"""
    return CALIBRATION_TASKS[task_type]


def get_all_task_types() -> List[CalibrationTaskType]:
    """Get list of all task types (in execution order)"""
    return [
        CalibrationTaskType.IMU_INTRINSIC,
        CalibrationTaskType.CAM_LR_FRONT_INTRINSIC,
        CalibrationTaskType.CAM_LR_FRONT_EXTRINSIC,
        CalibrationTaskType.CAM_LR_EYE_INTRINSIC,
        CalibrationTaskType.CAM_LR_EYE_EXTRINSIC,
        CalibrationTaskType.CAM_L_INTRINSIC,
        CalibrationTaskType.CAM_L_EXTRINSIC,
        CalibrationTaskType.CAM_R_INTRINSIC,
        CalibrationTaskType.CAM_R_EXTRINSIC,
    ]

